import { MainAppContext } from '@/appContext/MainAppContext';
import './globals.css'
import { ReduxProvider } from '@/Redux/provider';
import { SocketProvider } from '@/socket';


export const metadata = {
  title: 'Tacky Toe',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <MainAppContext>
            <SocketProvider>
            {children}
          </SocketProvider>
          </MainAppContext>
        </ReduxProvider>
      </body>
    </html>
  );
}
