import './globals.css'
import {configureStore } from "@reduxjs/toolkit"
import {Provider} from "react-redux"

export const metadata = {
  title: 'Tacky Toe',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
